### PR TITLE
Issue #89 Add support for array query parameters

### PR DESCRIPTION
**Pull request by romanzes**

### CODE REVIEW

**Comment by romanzes** [comment]
@kevinsawicki Any update on this?

**Comment by kevinsawicki** [comment]
Sorry for the delay, will merge and release soon, thanks for the nudge.

**Comment by kevinsawicki** [comment]
Thanks for adding this.

**Comment by kevinsawicki** [comment]
This has been release in 6.0

**Comment by romanzes** [comment]
Nice!

**Pull request merged**
